language: node_js
node_js:
  - "9"
cache: yarn
script:
  - gatsby build
deploy:
  provider: s3
  bucket: trafficdesign.pl
  region: website.eu-central-1
  skip_cleanup: true
  local_dir: public
  access_key_id:
    secure: 6Ta0NsilQXpQ2Q8BNpDiC9VL/ot4czW0KV+WF3HoweTLgR3QndcQVv0rh3xWZDwqO3QxwhZhMAcmVJiEY2EUU8hyEUQK5NzyvpJMjWg6Ye1+uwz141AQijASpaEwDImm5rubu+l9gcbekpUGnBgvAXqZrgCVo2TVUlepQG1+ObulcJrzowMpbTNaMyXjBXQkNLgYxWqnBSWkOrlGFf3+WPg49c9bMi7BRhtlyf+lx3soE+Nth618ntA+nnhwIjV/znxvJ6KhdYgMSoY60FlaVCy6NoJZDiMCdQ18GCrm+nI7JD+C/4/cbajLFnJD1AY63hDpUJw5YtePCGfQKA9R0PsiCktNIIC9Bvi/USW9u/TpQXukx1pBeWD/YfzspqC03MH56E+3jOiiTorN0g9CVwlmyyCRTNG5VXHB0ZYJvs/Nc38HffA6DTOURM0E9OV5MlztMxbtYcHf7A77IzGKWrDfysn4nPJ2n1jNeqZ0eG2HwdURU5WFbxi9Mj8zlqX6oFWxU3Z9ytftMYcDOVDDpacWUfJvwMcn+tR9f3hJUt3MKEOF1hggCOOP9/xxOwMXrqoo4j6DT0ykBz5W67Qok5ftR9QJJemEd5obhKIeI7euTazWjJlPd6KO215Z2JfmKySbNwf2y1RTAIFWJs2dWKYI3x9Gf3XHOdG2wlCcijk=
  secret_access_key:
    secure: k9oeODKgAANuGkoHL0SsHEE9Ne91OJDYXTisAaHhPLvdZwFINtZFG0LUTXGzzaMlnOVtPlLQZhzv0/IPQH3oNPV3z/nZAxomCJkwCGYAuulrSAiCN1wJ2SJvw9rwBC5QXnU5aI+lBFT2sQQNbqd6hofD1BKBDD/G9kg50rdGmLkJ1GJA888eMMo6uWBUbsU6eBQdFCdcGTlgaOFGBqpEd9D5e4bBhkDq1mJ/wycrdJbuP/2BOt3x/ukilf5KYtp+6JmKJUJrfRmUxh18/ds6oJG/0iXByhtZWZYcGH3oAI/rTw5fRJwr/DGW2W76LPwNFr0b+fqWelpudgHhZhWYoyeYHKw2NXpq/LFCm4/YcGB/RuWwP1R8v0KVtp+U130bZjx5qFJGmHam8DGed7zrAGQS2HACa1Y0eSnbENHUScXAciiqIDbP0bk70Rxy2HsJcG/31b1+lPa1MFmBvloty0xXziGe2EN7+Who7SrYjXzGtCLAFjfjtzysYByky5hYjLDAHCzdMn32ccnbAwSHS+U17jPt2oCKlYP1UwJfc/wgnYjhwpmQricVccz+jhYrykojufDJxohqcaG/jBnWqrGVS+cx8uyPi6dNCqUHN123AZQm5aOaqI1IazaIXT1YVOnQd7HSDbxH2AmWdWjRY/ZmJTt+dJyHcliSJ0JPJBM=
